### ISSUE TITLE
where did you incorporate the argument role special tokens in the summarization model?

### ISSUE THREAD

**Issue by HuyenNguyenHelen** [EngSalem/arglegalsumm#1]
Could you please show how you added the argument-role special tokens in the summarization model? Thank you so much.

**Comment by EngSalem** [comment]
Thank you for your interest
As mentioned in the paper , we highlight the sentence with the special markers  
For example: an issue sentence like "[6] Mr. Comeau appeals, arguing that
the probate court judge erred:" will become " < Issue >  [6] Mr. Comeau appeals, arguing that
the probate court judge erred: </ Issue >"

**Comment by HuyenNguyenHelen** [comment]
Thank you for your response. Does that mean you only added those special markers to the raw document input rather than adding a new masking layer?

**Comment by EngSalem** [comment]
No we don't do any masking, we add it as part of the vocabulary.

**Comment by HuyenNguyenHelen** [comment]
I got it. Thank you!
